kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: acn
  namespace: acn
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'acn:latest'
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:12-ubi8'
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: 'https://github.com/mparram/openshift-web-console-customizations.git'
      ref: master
    contextDir: /competition/mparram/code/
  runPolicy: Serial