kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acn
rules:
  - verbs:
      - '*'
    apiGroups:
      - console.openshift.io
    resources:
      - apiconsolenotifications
      - consolenotifications