kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acn
subjects:
  - kind: ServiceAccount
    name: acn
    namespace: acn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acn