apiVersion: console.openshift.io/v1
kind: APIConsoleNotification
metadata:
  name: openshifttv
spec:
  JSONPath: 'chatters.broadcaster[0]'
  consolenotification:
    backgroundColor: '#de3500'
    color: '#fff'
    link:
      href: 'https://www.twitch.tv/redhatopenshift'
      text: Openshift Twitch channel
    location: BannerTop
    name: openshifttv
    text: >-
      Openshift.tv is going live! - Follow Chris Short & Co. to understand what
      the hell are you doing.
  endpoint:
    headers: {}
    url: 'https://tmi.twitch.tv/group/user/redhatopenshift/chatters'
