kind: Deployment
apiVersion: apps/v1
metadata:
  name: acn
  namespace: acn
  labels:
    app: acn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acn
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: acn
        deploymentconfig: acn
    spec:
      restartPolicy: Always
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: download-custom-tools
          command:
            - sh
            - '-c'
          imagePullPolicy: Always
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools
          terminationMessagePolicy: File
          image: 'quay.io/openshift/origin-cli:latest'
          args:
            - cp /usr/bin/oc /custom-tools/oc
      serviceAccountName: acn
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: acn
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/oc
              subPath: oc
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/acn/acn:latest
      serviceAccount: acn
      volumes:
        - name: custom-tools
          emptyDir: {}
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600