kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acn-argocd
  namespace: argocd
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects