kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acn-argocd
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: acn
    namespace: acn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acn-argocd